version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "80:5000"
      # - "443:5000"

    environment:
      - APP_ENV=test

      - DB_NAME=vulnerable_bank_test
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      # Code decides which database to use based on APP_ENV
      # Main database
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/vulnerable_bank

      # Testing database for pytest
      - TEST_DATABASE_URL=postgresql://postgres:postgres@db:5432/vulnerable_bank_test
    depends_on:
      - db
    volumes:
      - ./static/uploads:/app/static/uploads
    networks:
      - vuln_network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=vulnerable_bank
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vuln_network

volumes:
  postgres_data:

networks:
  vuln_network:
    driver: bridge

