version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "80:5000"
      # - "443:5000" 

    environment:
      - DB_NAME=vulnerable_bank
      - DB_USER=vuln_user
      - DB_PASSWORD=vulnbank123
      - DB_HOST=db 
      - DB_PORT=5432
      - AI_BACKEND=ollama
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=deepseek-r1:1.5b
      - SECURITY_HARDENING_ENABLED=false
      - FLASK_SECRET_KEY=secret123
      - JWT_SECRET_KEY=secret123
    depends_on:
      - db
      - ollama
    volumes:
      - ./static/uploads:/app/static/uploads
    networks:
      - vuln_network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=vulnerable_bank
      - POSTGRES_USER=vuln_user
      - POSTGRES_PASSWORD=vulnbank123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vuln_network

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - vuln_network

volumes:
  postgres_data:
  ollama_data:

networks:
  vuln_network:
    driver: bridge